### ISSUE TITLE
Updating old content with Funder names to add to funder registry

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-crossref-feed#120]
See: https://support.crossref.org/hc/en-us/articles/215788243

**Comment by Melissa37** [comment]
Note, from Crossref:

We will try to match funder names to IDs upon deposit if one is not provided, and we insert the IDs we identify into our metadata outputs.  This is reflected in the deposit logs and is carried over into metadata outputs.  In the REST API output we flag whether or not a funder ID was asserted by a publisher or Crossref ('doi-asserted-by' in the 'funder' section), we also have an API that will identify matched funders (see link above).

So conclusions: 
No need to add validation step into our process (checking funder registry for matches in the XML that do not contain IDs)
Would be good to use this service to go through the archive and update old content without IDs that now have them

**Comment by gnott** [comment]
If you can please clarify @Melissa37, for the eLife archive are you proposing to
a) look up funder ID values and add them to the article XML?
b) look up funder ID values and display them on the web journal pages?
c) look up funder ID values (optionally) when generating Crossref deposits and add them, rather than relying on Crossref to search for the values?

It looks useful the funder API `q` query variable seems to support funder names, such as http://doi.crossref.org/getFunders?q=Howard%20Hughes%20Medical%20Institute

```
{
  "searchedName" : "Howard Hughes Medical Institute",
  "funder-info" : [
    {
      "suggested" : [
        {
          "isRegistryName" : "true",
          "identifier" : "10.13039/100000011",
          "country" : "United States",
          "prefLabel" : "Howard Hughes Medical Institute"
        }
      ]
    }
  ]
}
```

**Comment by Melissa37** [comment]
Hi Graham

I just realised how thick I was being - we're going to redeposit the archive so they will "try to match funder names to IDs upon deposit if one is not provided" when we do that, so they can do this and we need no logic and don't have to do it!!

Durhh, sorry. I think we can close this ticket?

M

**Comment by gnott** [comment]
Converting funder names to ID values via the API might be more useful in another project, since the ones in Crossref deposits will get converted already. 

It might be good to catch an incorrect funder name before generating the deposit output? Those would be caught later I guess after depositing to Crossref. Even so, I think that would be a later enhancement?

**Comment by Melissa37** [comment]
"catch an incorrect funder name" - would be interesting how to do this automatically as we're doing this manually in editorial and production.

But agree, another time/project
