### ISSUE TITLE
Figures with a different license, AccessIndicators or alternate

### ISSUE THREAD

**Issue by gnott** [elifesciences/elife-crossref-feed#53]
Somewhat related to issue #52, access indicators work fine as intended for the license of the overall article.

2050-084X_2013_elife00178.xml  sample file does not validate specifically where it uses in Figure 1:

```
<ai:program>
<ai:license_ref>© 1977 Thieme Medical Publishers. All Rights Reserved. Figure 1, lower panel, is reproduced from Hughes and Sperandio, 2008 with permission.</ai:license_ref>
<ai:license_ref>© 2007 Elsevier Masson SAS. All rights reserved. The patient figure in Figure 6, part A is reproduced from Koropatnick et al., 2004, European Journal of Medical Genetics with permission.</ai:license_ref>
</ai:program>
```

``<ai:license>`` must contain a valid URI only.

Some possible solutions, there may be more options:

1. Use the ``<component><description>`` tag and put the license data in the description tag
1. Insert a URI for the license (if there is an appropriate license we can set automatically)
1. Remove the ``<ai:program>`` from from component entirely

**Comment by Melissa37** [comment]
That's weird, it validates for me (the XML in the repo).
I'll send you the complete package of CrossRef schema etc that I have locally so you can test too...maybe something was updated that you don't have locally?

**Comment by gnott** [comment]
I use the online validator too when testing, uploading to http://www.crossref.org/02publishers/parser.html

I think it is reporting an error validating against http://www.crossref.org/schemas/AccessIndicators.xsd; ``<license_ref_t>`` requires a string matching the pattern starting with http: https: etc.

**Comment by Melissa37** [comment]
Response from CrossRef:

Our validation tool does validate against the current versions of our schema.

jats:abstract
We haven't updated either schema for months, crossref4.3.5.xsd was last updated February 24 to allow multiple abstracts at your request. If your local copy doesn't have maxOccurs="unbounded" then it needs to be updated with our version.

AccessIndicators.xsd
This was updated in April, as you noticed we don't increment schema numbers.

I try to announce any changes that make schema backwards-incompatible. This change wasn't made by me and it fell through the cracks, unfortunately - we do require that license_ref values be a URL to a license, and not the license itself.

We very strongly recommend that validation be done against our schema and not locally. I do agree that we should increment schema numbers when changes are made, there are some technical reasons we don't do that but (as you've noticed!) it causes problems. I'll raise the issue again internally. In the past our schema changes have been very infrequent so it hasn't been an issue, but that is no longer the case.

-Patricia

I have asked:

Thanks so much for the quick response. 
The issue of license_ref values be a URL to a license is a bit of a problem as the reason we need to hook out these sub-DOIs is because they are not CC-BY and do not have a specific license, and this needs to be indicated. This will affect text and data mining when we join up.

Would the suggestion be that eLife creates a url to put into these specific fields and this leads to a page indicating that items are not CC-BY?

How are other publishers dealing with this requirement? Or is our use-case so unique?

**Comment by Melissa37** [comment]
Response from CrossRef: Patricia Feeney (CrossRef Support)
Aug 26, 16:57

Hi Melissa,

That's a good question! I think that linking to a page as you describe is appropriate, I am cc'ing Rachael as she might have more insight into how other publishers handle this situation.

-Patricia

**Comment by Melissa37** [comment]
Moved to JIRA: http://jira.elifesciences.org:8080/browse/ELPP-916
